name: laravel-nginx
type: service
from: php-nginx
title: Nginx (Laravel)

update: auto
    
labels:
- laravel

build:
  dockerfile: Dockerfile

settings:
- name: docroot
  title: Nginx docroot
  default: public
  var: DOCROOT_SUBDIR

configs:
- name: preset
  title: Laravel preset
  filepath: /etc/gotpl/preset/laravel.conf.tmpl
  config: preset.conf.tmpl

volumes:
- name: storage
  from: backend
  title: Storage
  path: /mnt/files

env:
- name: NGINX_VHOST_PRESET
  value: laravel
