name: laravel-nginx
type: service
from: php-nginx
title: Nginx (Laravel)

update: auto
    
labels:
- laravel

settings:
- name: docroot
  title: Nginx docroot
  default: public
  var: DOCROOT_SUBDIR

volumes:
- name: storage
  from: backend
  title: Storage
  path: /mnt/files

env:
- name: NGINX_VHOST_PRESET
  value: laravel
