name: laravel-nginx
type: service
from: php-nginx
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.2"
title: Nginx (Laravel)


labels:
- laravel

build:
  dockerfile: Dockerfile

settings:
- name: docroot
  title: Nginx docroot
  default: public
  var: DOCROOT_SUBDIR
  build: true

configs:
- name: preset
  title: Laravel preset
  filepath: /etc/gotpl/preset/laravel.conf.tmpl
  config: preset.conf.tmpl
- name: preset
  title: Laravel preset
  filepath: /etc/gotpl/preset/laravel.conf.tmpl
  config: preset.conf.1.27.tmpl
  version: '1.27'
- name: preset
  title: Laravel preset
  filepath: /etc/gotpl/preset/laravel.conf.tmpl
  config: preset.conf.tmpl
  version: '1.25'

volumes:
- name: storage
  from: backend
  title: Storage
  path: /mnt/files

env:
- name: NGINX_VHOST_PRESET
  value: laravel
