name: nginx-laravel
type: service
from: nginx-php
title: Nginx (Laravel)

update: auto
    
labels:
- laravel

settings:
- name: docroot
  title: Nginx docroot
  default: public
  var: DOCROOT_SUBDIR

env:
- name: NGINX_VHOST_PRESET
  value: php
